name: Despertador Pollito 🐥
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  vigilar_plazas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - name: 🚀 Ejecutar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: main.py
      - name: 💾 Guardar memoria
        run: |
          git config --global user.name 'Bot Pollito'
          git config --global user.email 'pollito@bot.com'
          git add memoria_pollito.json
          git commit -m "Actualizar libreta" || exit 0
          git push
